### ISSUE TITLE
Issues between robomasterpy and multiprocessing

### ISSUE THREAD

**Issue by siKruger** [nanmu42/robo-playground#5]
hi,

unfortunately both examples don't work for me. 
At least for me it seems like this is a issue with how robomasterpy works with pythons multiprocessing.
See the following error:

```
[h264 @ 000001a5ff495440] missing picture in access unit with size 6
2023-03-14 16:52:28,044 vision       : INFO     signal received, closing...
Process vision:
Traceback (most recent call last):
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\multiprocessing\managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\robomasterpy\framework.py", line 297, in _build_worker_and_run
    worker()
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\robomasterpy\framework.py", line 164, in __call__
    self.work()
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\robomasterpy\framework.py", line 559, in work
    self._outlet(processed)
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\robomasterpy\framework.py", line 193, in _outlet
    self._out.put(payload, block=True, timeout=self.QUEUE_TIMEOUT)
  File "<string>", line 2, in put
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\multiprocessing\managers.py", line 814, in _callmethod
    self._connect()
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\multiprocessing\managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\multiprocessing\connection.py", line 505, in Client
    c = PipeClient(address)
  File "C:\Users\eddiw\.pyenv\pyenv-win\versions\3.10.6\lib\multiprocessing\connection.py", line 707, in PipeClient
    _winapi.WaitNamedPipe(address, 1000)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by siKruger** [comment]
Well, as it turns out the problem is Line 318 in framework.py of robomasterpy. 

`signal.sigwait((signal.SIGINT, signal.SIGTERM))`
sigwait() is not known to python.

**Comment by nanmu42** [comment]
Thanks for the raise: https://github.com/nanmu42/robomasterpy/issues/25
